name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name : build main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Maven Build
        #run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=univ-smb-m1-isc-2021_hello-world
        run: mvn -B verify --file pom.xml

      - name: Maven Test
        run: mvn test --file pom.xml
        #env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}